# target specific for pico. need to update for others, but as this is just for pico, too bad
[target.thumbv6m-none-eabi]
runner = "elf2uf2-rs -d"

rustflags = [
    "-C", "inline-threshold=5",
    "-C", "no-vectorize-loops",
]

[build]
target = "thumbv6m-none-eabi"        # Cortex-M0 and Cortex-M0+
